import { query } from "./db.js";
import { runMigrations } from "./migrationRunner.js";

const BASE_CURRENCIES = [
  ["USD", "US Dollar", 2],
  ["EUR", "Euro", 2],
  ["TRY", "Turkish Lira", 2],
  ["GBP", "Pound Sterling", 2],
  ["AFN", "Afghan Afghani", 2],
  ["JPY", "Japanese Yen", 0],
  ["INR", "Indian Rupee", 2],
  ["CAD", "Canadian Dollar", 2],
  ["AUD", "Australian Dollar", 2],
  ["CHF", "Swiss Franc", 2],
  ["AED", "UAE Dirham", 2],
  ["SAR", "Saudi Riyal", 2],
  ["BRL", "Brazilian Real", 2],
  ["MXN", "Mexican Peso", 2],
  ["ZAR", "South African Rand", 2],
  ["SGD", "Singapore Dollar", 2],
];

const BASE_COUNTRIES = [
  ["US", "USA", "United States", "USD"],
  ["TR", "TUR", "Turkey", "TRY"],
  ["GB", "GBR", "United Kingdom", "GBP"],
  ["DE", "DEU", "Germany", "EUR"],
  ["AF", "AFG", "Afghanistan", "AFN"],
  ["FR", "FRA", "France", "EUR"],
  ["IT", "ITA", "Italy", "EUR"],
  ["ES", "ESP", "Spain", "EUR"],
  ["NL", "NLD", "Netherlands", "EUR"],
  ["CH", "CHE", "Switzerland", "CHF"],
  ["CA", "CAN", "Canada", "CAD"],
  ["AU", "AUS", "Australia", "AUD"],
  ["JP", "JPN", "Japan", "JPY"],
  ["IN", "IND", "India", "INR"],
  ["AE", "ARE", "United Arab Emirates", "AED"],
  ["SA", "SAU", "Saudi Arabia", "SAR"],
  ["BR", "BRA", "Brazil", "BRL"],
  ["MX", "MEX", "Mexico", "MXN"],
  ["ZA", "ZAF", "South Africa", "ZAR"],
  ["SG", "SGP", "Singapore", "SGD"],
];

const PERMISSIONS = [
  ["org.tree.read", "Read org hierarchy tree"],
  ["org.fiscal_calendar.read", "Read fiscal calendars"],
  ["org.fiscal_period.read", "Read fiscal periods"],
  ["org.group_company.upsert", "Create/update group companies"],
  ["org.legal_entity.upsert", "Create/update legal entities"],
  ["org.operating_unit.upsert", "Create/update operating units/branches"],
  ["org.fiscal_calendar.upsert", "Create/update fiscal calendars"],
  ["org.fiscal_period.generate", "Generate fiscal periods"],
  ["security.permission.read", "Read permission catalog"],
  ["security.role.read", "Read security roles"],
  ["security.role.upsert", "Create/update security roles"],
  ["security.role_permissions.assign", "Assign permissions to roles"],
  ["security.role_assignment.read", "Read role assignments"],
  ["security.role_assignment.upsert", "Assign roles to users and scopes"],
  ["security.data_scope.read", "Read user data scopes"],
  ["security.data_scope.upsert", "Create/update/delete user data scopes"],
  ["security.audit.read", "Read RBAC audit logs"],
  ["gl.book.read", "Read books"],
  ["gl.book.upsert", "Create/update books"],
  ["gl.coa.read", "Read chart of accounts"],
  ["gl.coa.upsert", "Create/update chart of accounts"],
  ["gl.account.read", "Read accounts"],
  ["gl.account.upsert", "Create/update accounts"],
  ["gl.account_mapping.upsert", "Create/update account mappings"],
  ["gl.journal.read", "Read journals"],
  ["gl.journal.create", "Create journals"],
  ["gl.journal.post", "Post journals"],
  ["gl.journal.reverse", "Reverse posted journals"],
  ["gl.trial_balance.read", "Read trial balance"],
  ["gl.period.close", "Close accounting periods"],
  ["cash.register.read", "Read cash registers"],
  ["cash.register.upsert", "Create/update cash registers"],
  ["cash.session.open", "Open cash sessions"],
  ["cash.session.close", "Close cash sessions"],
  ["cash.txn.read", "Read cash transactions"],
  ["cash.txn.create", "Create cash transactions"],
  ["cash.txn.cancel", "Cancel draft/submitted cash transactions"],
  ["cash.txn.post", "Post cash transactions"],
  ["cash.txn.reverse", "Reverse posted cash transactions"],
  ["cash.override.post", "Post cash entries with cash-control override"],
  ["cash.variance.approve", "Approve cash session variances"],
  ["cash.report.read", "Read cash reports"],
  ["bank.accounts.read", "Read bank account master records and GL links"],
  ["bank.accounts.write", "Create/update/activate/deactivate bank account master records"],
  ["bank.connectors.read", "Read bank connector masters, account links, and sync run logs (B05)"],
  ["bank.connectors.write", "Create/update bank connector masters and connector-account mappings (B05)"],
  ["bank.connectors.sync", "Test bank connectors and pull statement feeds via B02 import pipeline (B05)"],
  ["bank.statements.import", "Import bank statement files and create normalized bank statement lines"],
  ["bank.statements.read", "Read bank statement imports and normalized statement line queue"],
  ["bank.reconcile.read", "Read bank reconciliation queue, suggestions, and audit trail"],
  ["bank.reconcile.write", "Create/reverse bank reconciliation matches and ignore actions"],
  ["bank.reconcile.templates.read", "Read bank reconciliation auto-posting templates (B08-A)"],
  ["bank.reconcile.templates.write", "Create/update bank reconciliation auto-posting templates (B08-A)"],
  ["bank.reconcile.diffprofiles.read", "Read bank reconciliation difference profiles (B08-B)"],
  ["bank.reconcile.diffprofiles.write", "Create/update bank reconciliation difference profiles (B08-B)"],
  ["bank.reconcile.rules.read", "Read bank reconciliation automation rules (B07)"],
  ["bank.reconcile.rules.write", "Create/update bank reconciliation automation rules (B07)"],
  ["bank.reconcile.auto.run", "Run bank reconciliation automation preview/apply (B07)"],
  ["bank.reconcile.exceptions.read", "Read bank reconciliation exception queue (B07)"],
  ["bank.reconcile.exceptions.write", "Assign/resolve/ignore/retry bank reconciliation exceptions (B07)"],
  ["payments.batch.read", "Read generic payment batches, lines, exports, and audit"],
  ["payments.batch.create", "Create generic payment batches"],
  ["payments.batch.approve", "Approve generic payment batches (maker-checker)"],
  ["payments.batch.export", "Export generic payment batches to payment files (v1 CSV)"],
  ["payments.batch.post", "Post generic payment batch settlement journals"],
  ["payments.batch.cancel", "Cancel non-posted generic payment batches"],
  ["bank.payments.export.read", "Read bank-facing payment file export runs for generic payment batches"],
  ["bank.payments.export.create", "Create bank-facing payment files (B06 wrapper export) for generic payment batches"],
  ["bank.payments.ack.read", "Read imported bank acknowledgement files for generic payment batches"],
  ["bank.payments.ack.import", "Import bank acknowledgement files and update payment execution status (B06)"],
  ["bank.payments.returns.read", "Read bank payment return/rejection events (B08-B)"],
  ["bank.payments.returns.write", "Create/ignore bank payment return/rejection events (B08-B)"],
  ["bank.approvals.policies.read", "Read bank governance approval policies (B09)"],
  ["bank.approvals.policies.create", "Create bank governance approval policies (B09)"],
  ["bank.approvals.policies.update", "Update bank governance approval policies (B09)"],
  ["bank.approvals.requests.read", "Read bank governance approval request queue and decisions (B09)"],
  ["bank.approvals.requests.submit", "Submit manual bank approval requests (B09)"],
  ["bank.approvals.requests.approve", "Approve bank governance requests (B09)"],
  ["bank.approvals.requests.reject", "Reject bank governance requests (B09)"],
  ["bank.approvals.requests.approve.payment", "Approve bank payment export/release requests (B09)"],
  ["bank.approvals.requests.approve.reconConfig", "Approve bank reconciliation rule/template/profile changes (B09)"],
  ["bank.approvals.requests.approve.reconOverride", "Approve bank reconciliation exception override requests (B09)"],
  ["bank.approvals.requests.approve.manualReturn", "Approve bank manual return/rejection creation requests (B09)"],
  ["approvals.policies.read", "Read unified approval policies across bank and payroll (H04)"],
  ["approvals.policies.write", "Create/update unified approval policies across bank and payroll (H04)"],
  ["approvals.requests.read", "Read unified approval requests and decisions across bank and payroll (H04)"],
  ["approvals.requests.submit", "Submit unified approval requests manually (H04)"],
  ["approvals.requests.approve", "Approve unified approval requests (H04)"],
  ["approvals.requests.reject", "Reject unified approval requests (H04)"],
  ["payroll.runs.read", "Read payroll runs, lines, and payroll import audit trail"],
  ["payroll.runs.import", "Import payroll provider CSV into payroll subledger runs"],
  ["payroll.provider.read", "Read payroll provider adapters, connections, employee refs, and import jobs"],
  ["payroll.provider.write", "Create/update payroll provider connections"],
  ["payroll.provider.mapping.read", "Read payroll external employee to internal employee mappings"],
  ["payroll.provider.mapping.write", "Create/update payroll external employee to internal employee mappings"],
  ["payroll.provider.import.read", "Read payroll provider import preview/apply jobs and audit trail"],
  ["payroll.provider.import.preview", "Preview payroll provider imports and store normalized canonical payloads"],
  ["payroll.provider.import.apply", "Apply payroll provider import previews into payroll runs (maker-checker)"],
  ["payroll.provider.import.retention.manage", "Mask/purge raw payload retention for payroll provider import jobs"],
  ["bank.integration.retention.manage", "Mask/purge raw payload retention for bank integration feeds/webhooks/imports"],
  ["security.sensitive_data.audit.read", "Read sensitive data lifecycle audit trail (encryption, masking, purging)"],
  ["ops.jobs.read", "Read tenant-scoped background jobs and attempts"],
  ["ops.jobs.manage", "Cancel/requeue tenant-scoped background jobs"],
  ["ops.jobs.run", "Run one tenant-scoped background job manually (admin/ops)"],
  ["ops.dashboard.read", "Read operational dashboard KPI/SLA/health summaries"],
  ["ops.exceptions.read", "Read unified exception workbench queue and audit"],
  ["ops.exceptions.manage", "Claim/resolve/ignore/reopen unified exceptions"],
  ["ops.retention.read", "Read data retention policies/runs and retention execution history (H07)"],
  ["ops.retention.manage", "Create/update/execute data retention policies and runs (H07)"],
  ["ops.export_snapshot.read", "Read closed-period immutable export snapshots and hashes (H07)"],
  ["ops.export_snapshot.create", "Create immutable export snapshots for closed payroll periods (H07)"],
  ["payroll.mappings.read", "Read effective-dated payroll component to GL mappings"],
  ["payroll.mappings.write", "Create/update payroll component to GL mappings"],
  ["payroll.runs.review", "Mark payroll runs as reviewed before accrual posting"],
  ["payroll.runs.finalize", "Finalize payroll runs and post accrual journals to GL"],
  ["payroll.liabilities.read", "Read payroll liabilities, run-level liability summaries, and audit"],
  ["payroll.liabilities.build", "Build payroll liabilities from finalized payroll runs"],
  ["payroll.payment.prepare", "Prepare generic payment batches from payroll liabilities"],
  ["payroll.payment.sync.read", "Preview payroll liability settlement sync from payments and bank reconciliation"],
  ["payroll.payment.sync.apply", "Apply payroll liability settlement sync from payments and bank reconciliation"],
  ["payroll.settlement.override.read", "Read payroll manual settlement override requests and liability override history"],
  ["payroll.settlement.override.request", "Create payroll manual settlement override requests (maker)"],
  ["payroll.settlement.override.approve", "Approve/apply or reject payroll manual settlement override requests (checker)"],
  ["payroll.beneficiary.read", "Read payroll beneficiary bank master accounts"],
  ["payroll.beneficiary.write", "Create/update payroll beneficiary bank master accounts"],
  ["payroll.beneficiary.set_primary", "Set primary payroll beneficiary bank account"],
  ["payroll.beneficiary.snapshot.read", "Read payroll liability beneficiary bank snapshots"],
  ["payroll.close.read", "Read payroll close controls, checklist results, and close audit"],
  ["payroll.close.prepare", "Prepare payroll close checklist and lock flags for a payroll period"],
  ["payroll.close.request", "Request payroll period close after checklist passes (maker)"],
  ["payroll.close.approve", "Approve and close payroll period after request (checker)"],
  ["payroll.close.reopen", "Reopen closed payroll period close controls and release locks"],
  ["payroll.corrections.read", "Read payroll correction links, reversal runs, and correction shell relationships"],
  ["payroll.corrections.create", "Create payroll correction shells (OFF_CYCLE/RETRO)"],
  ["payroll.corrections.reverse", "Reverse finalized payroll runs and create linked reversal runs"],
  ["cari.card.read", "Read counterparty (cari) cards"],
  ["cari.card.upsert", "Create/update counterparty (cari) cards"],
  ["cari.doc.read", "Read Cari documents"],
  ["cari.doc.create", "Create Cari documents"],
  ["cari.doc.update", "Update draft Cari documents"],
  ["cari.doc.post", "Post Cari documents"],
  ["cari.doc.reverse", "Reverse posted Cari documents"],
  ["cari.settlement.apply", "Apply Cari settlement allocations"],
  ["cari.settlement.reverse", "Reverse Cari settlement batches"],
  ["cari.report.read", "Read Cari reports"],
  ["cari.fx.override", "Override Cari FX rates during posting/settlement"],
  ["cari.audit.read", "Read Cari audit trail"],
  ["cari.bank.attach", "Attach Cari records to bank lines"],
  ["cari.bank.apply", "Apply Cari bank-linked settlements/unapplied cash"],
  ["contract.read", "Read contracts and linked document summaries"],
  ["contract.upsert", "Create/update draft contracts and line sets"],
  ["contract.activate", "Activate contracts"],
  ["contract.suspend", "Suspend active contracts"],
  ["contract.close", "Close contracts"],
  ["contract.cancel", "Cancel draft contracts"],
  ["contract.link_document", "Create contract-document links"],
  ["revenue.schedule.read", "Read revenue-recognition schedules"],
  ["revenue.schedule.generate", "Generate revenue-recognition schedules"],
  ["revenue.run.read", "Read revenue-recognition runs"],
  ["revenue.run.create", "Create revenue-recognition runs"],
  ["revenue.run.post", "Post revenue-recognition runs"],
  ["revenue.run.reverse", "Reverse revenue-recognition runs"],
  ["revenue.report.read", "Read revenue-recognition reports"],
  ["fx.rate.bulk_upsert", "Bulk upsert FX rates"],
  ["fx.rate.read", "Read FX rates"],
  ["intercompany.flag.read", "Read legal entity intercompany flags"],
  ["intercompany.flag.upsert", "Create/update legal entity intercompany flags"],
  ["intercompany.pair.upsert", "Create/update intercompany pairs"],
  ["intercompany.reconcile.run", "Run intercompany reconciliation"],
  ["consolidation.group.read", "Read consolidation groups"],
  ["consolidation.group.upsert", "Create/update consolidation groups"],
  ["consolidation.group_member.upsert", "Create/update consolidation members"],
  ["consolidation.coa_mapping.read", "Read group CoA mappings"],
  ["consolidation.coa_mapping.upsert", "Create/update group CoA mappings"],
  ["consolidation.elimination_placeholder.read", "Read elimination placeholders"],
  ["consolidation.elimination_placeholder.upsert", "Create/update elimination placeholders"],
  ["consolidation.run.read", "Read consolidation runs"],
  ["consolidation.run.create", "Create consolidation runs"],
  ["consolidation.run.execute", "Execute consolidation runs"],
  ["consolidation.elimination.create", "Create elimination entries"],
  ["consolidation.elimination.post", "Post elimination entries"],
  ["consolidation.adjustment.create", "Create consolidation adjustments"],
  ["consolidation.adjustment.post", "Post consolidation adjustments"],
  ["consolidation.run.finalize", "Finalize consolidation runs"],
  ["consolidation.report.trial_balance.read", "Read consolidation trial balance"],
  ["consolidation.report.summary.read", "Read consolidation summary report"],
  ["consolidation.report.balance_sheet.read", "Read consolidation balance sheet"],
  ["consolidation.report.income_statement.read", "Read consolidation income statement"],
  ["onboarding.company.setup", "Run company onboarding bootstrap flow"],
];

const ROLE_DEFINITIONS = [
  {
    code: "TenantAdmin",
    name: "Tenant Administrator",
    permissions: PERMISSIONS.map(([code]) => code),
  },
  {
    code: "GroupController",
    name: "Group Controller",
    permissions: [
      "org.tree.read",
      "org.fiscal_calendar.read",
      "org.fiscal_period.read",
      "org.group_company.upsert",
      "org.legal_entity.upsert",
      "org.operating_unit.upsert",
      "org.fiscal_calendar.upsert",
      "org.fiscal_period.generate",
      "gl.book.read",
      "gl.coa.read",
      "gl.account.read",
      "gl.journal.read",
      "gl.trial_balance.read",
      "cash.register.read",
      "bank.accounts.read",
      "bank.connectors.read",
      "bank.statements.read",
      "bank.reconcile.read",
      "bank.reconcile.templates.read",
      "bank.reconcile.diffprofiles.read",
      "bank.reconcile.rules.read",
      "bank.reconcile.exceptions.read",
      "payments.batch.read",
      "bank.payments.export.read",
      "bank.payments.ack.read",
      "bank.payments.returns.read",
      "bank.approvals.policies.read",
      "bank.approvals.requests.read",
      "approvals.policies.read",
      "approvals.requests.read",
      "payroll.runs.read",
      "payroll.provider.read",
      "payroll.provider.mapping.read",
      "payroll.provider.import.read",
      "security.sensitive_data.audit.read",
      "ops.jobs.read",
      "ops.dashboard.read",
      "ops.exceptions.read",
      "ops.retention.read",
      "ops.export_snapshot.read",
      "payroll.mappings.read",
      "payroll.liabilities.read",
      "payroll.payment.sync.read",
      "payroll.settlement.override.read",
      "payroll.beneficiary.read",
      "payroll.beneficiary.snapshot.read",
      "payroll.close.read",
      "payroll.corrections.read",
      "cash.txn.read",
      "cash.variance.approve",
      "cash.report.read",
      "cari.card.read",
      "cari.doc.read",
      "cari.report.read",
      "cari.audit.read",
      "contract.read",
      "revenue.schedule.read",
      "revenue.schedule.generate",
      "revenue.run.read",
      "revenue.run.create",
      "revenue.run.post",
      "revenue.run.reverse",
      "revenue.report.read",
      "intercompany.flag.read",
      "intercompany.flag.upsert",
      "fx.rate.read",
      "intercompany.pair.upsert",
      "intercompany.reconcile.run",
      "consolidation.group.read",
      "consolidation.group.upsert",
      "consolidation.group_member.upsert",
      "consolidation.coa_mapping.read",
      "consolidation.coa_mapping.upsert",
      "consolidation.elimination_placeholder.read",
      "consolidation.elimination_placeholder.upsert",
      "consolidation.run.read",
      "consolidation.run.create",
      "consolidation.run.execute",
      "consolidation.elimination.create",
      "consolidation.elimination.post",
      "consolidation.adjustment.create",
      "consolidation.adjustment.post",
      "consolidation.run.finalize",
      "consolidation.report.trial_balance.read",
      "consolidation.report.summary.read",
      "consolidation.report.balance_sheet.read",
      "consolidation.report.income_statement.read",
    ],
  },
  {
    code: "CountryController",
    name: "Country Controller",
    permissions: [
      "org.tree.read",
      "org.fiscal_calendar.read",
      "org.fiscal_period.read",
      "org.legal_entity.upsert",
      "org.operating_unit.upsert",
      "gl.book.read",
      "gl.book.upsert",
      "gl.coa.read",
      "gl.coa.upsert",
      "gl.account.read",
      "gl.account.upsert",
      "gl.account_mapping.upsert",
      "gl.journal.read",
      "gl.journal.create",
      "gl.journal.post",
      "gl.journal.reverse",
      "gl.trial_balance.read",
      "gl.period.close",
      "cash.register.read",
      "cash.register.upsert",
      "cash.session.open",
      "cash.session.close",
      "cash.txn.read",
      "cash.txn.create",
      "cash.txn.cancel",
      "cash.txn.post",
      "cash.txn.reverse",
      "cash.override.post",
      "cash.variance.approve",
      "cash.report.read",
      "bank.accounts.read",
      "bank.accounts.write",
      "bank.connectors.read",
      "bank.connectors.write",
      "bank.connectors.sync",
      "bank.statements.import",
      "bank.statements.read",
      "bank.reconcile.read",
      "bank.reconcile.write",
      "bank.reconcile.templates.read",
      "bank.reconcile.templates.write",
      "bank.reconcile.diffprofiles.read",
      "bank.reconcile.diffprofiles.write",
      "bank.reconcile.rules.read",
      "bank.reconcile.rules.write",
      "bank.reconcile.auto.run",
      "bank.reconcile.exceptions.read",
      "bank.reconcile.exceptions.write",
      "payments.batch.read",
      "payments.batch.create",
      "payments.batch.approve",
      "payments.batch.export",
      "payments.batch.post",
      "payments.batch.cancel",
      "bank.payments.export.read",
      "bank.payments.export.create",
      "bank.payments.ack.read",
      "bank.payments.ack.import",
      "bank.payments.returns.read",
      "bank.payments.returns.write",
      "bank.approvals.policies.read",
      "bank.approvals.policies.create",
      "bank.approvals.policies.update",
      "bank.approvals.requests.read",
      "bank.approvals.requests.submit",
      "bank.approvals.requests.approve",
      "bank.approvals.requests.reject",
      "bank.approvals.requests.approve.payment",
      "bank.approvals.requests.approve.reconConfig",
      "bank.approvals.requests.approve.reconOverride",
      "bank.approvals.requests.approve.manualReturn",
      "approvals.policies.read",
      "approvals.policies.write",
      "approvals.requests.read",
      "approvals.requests.submit",
      "approvals.requests.approve",
      "approvals.requests.reject",
      "payroll.runs.read",
      "payroll.runs.import",
      "payroll.provider.read",
      "payroll.provider.write",
      "payroll.provider.mapping.read",
      "payroll.provider.mapping.write",
      "payroll.provider.import.read",
      "payroll.provider.import.preview",
      "payroll.provider.import.apply",
      "payroll.provider.import.retention.manage",
      "bank.integration.retention.manage",
      "security.sensitive_data.audit.read",
      "ops.jobs.read",
      "ops.jobs.manage",
      "ops.jobs.run",
      "ops.dashboard.read",
      "ops.exceptions.read",
      "ops.exceptions.manage",
      "ops.retention.read",
      "ops.retention.manage",
      "ops.export_snapshot.read",
      "ops.export_snapshot.create",
      "payroll.mappings.read",
      "payroll.mappings.write",
      "payroll.runs.review",
      "payroll.runs.finalize",
      "payroll.liabilities.read",
      "payroll.liabilities.build",
      "payroll.payment.prepare",
      "payroll.payment.sync.read",
      "payroll.payment.sync.apply",
      "payroll.settlement.override.read",
      "payroll.settlement.override.request",
      "payroll.settlement.override.approve",
      "payroll.beneficiary.read",
      "payroll.beneficiary.write",
      "payroll.beneficiary.set_primary",
      "payroll.beneficiary.snapshot.read",
      "payroll.close.read",
      "payroll.close.prepare",
      "payroll.close.request",
      "payroll.close.approve",
      "payroll.close.reopen",
      "payroll.corrections.read",
      "payroll.corrections.create",
      "payroll.corrections.reverse",
      "cari.card.read",
      "cari.card.upsert",
      "cari.doc.read",
      "cari.doc.create",
      "cari.doc.update",
      "cari.doc.post",
      "cari.doc.reverse",
      "cari.settlement.apply",
      "cari.settlement.reverse",
      "cari.report.read",
      "cari.fx.override",
      "cari.bank.attach",
      "cari.bank.apply",
      "contract.read",
      "contract.upsert",
      "contract.activate",
      "contract.suspend",
      "contract.close",
      "contract.cancel",
      "contract.link_document",
      "revenue.schedule.read",
      "revenue.schedule.generate",
      "revenue.run.read",
      "revenue.run.create",
      "revenue.run.post",
      "revenue.run.reverse",
      "revenue.report.read",
      "intercompany.flag.read",
      "intercompany.flag.upsert",
      "fx.rate.read",
    ],
  },
  {
    code: "EntityAccountant",
    name: "Entity Accountant",
    permissions: [
      "org.tree.read",
      "org.fiscal_calendar.read",
      "org.fiscal_period.read",
      "gl.book.read",
      "gl.book.upsert",
      "gl.coa.read",
      "gl.coa.upsert",
      "gl.account.read",
      "gl.account.upsert",
      "gl.account_mapping.upsert",
      "gl.journal.read",
      "gl.journal.create",
      "gl.journal.post",
      "gl.journal.reverse",
      "gl.trial_balance.read",
      "gl.period.close",
      "cash.register.read",
      "bank.accounts.read",
      "bank.accounts.write",
      "bank.connectors.read",
      "bank.connectors.write",
      "bank.connectors.sync",
      "bank.statements.import",
      "bank.statements.read",
      "bank.reconcile.read",
      "bank.reconcile.write",
      "bank.reconcile.templates.read",
      "bank.reconcile.templates.write",
      "bank.reconcile.diffprofiles.read",
      "bank.reconcile.diffprofiles.write",
      "bank.reconcile.rules.read",
      "bank.reconcile.rules.write",
      "bank.reconcile.auto.run",
      "bank.reconcile.exceptions.read",
      "bank.reconcile.exceptions.write",
      "payments.batch.read",
      "payments.batch.create",
      "payments.batch.approve",
      "payments.batch.export",
      "payments.batch.post",
      "payments.batch.cancel",
      "bank.payments.export.read",
      "bank.payments.export.create",
      "bank.payments.ack.read",
      "bank.payments.ack.import",
      "bank.payments.returns.read",
      "bank.payments.returns.write",
      "bank.approvals.policies.read",
      "bank.approvals.policies.create",
      "bank.approvals.policies.update",
      "bank.approvals.requests.read",
      "bank.approvals.requests.submit",
      "bank.approvals.requests.approve",
      "bank.approvals.requests.reject",
      "bank.approvals.requests.approve.payment",
      "bank.approvals.requests.approve.reconConfig",
      "bank.approvals.requests.approve.reconOverride",
      "bank.approvals.requests.approve.manualReturn",
      "approvals.policies.read",
      "approvals.policies.write",
      "approvals.requests.read",
      "approvals.requests.submit",
      "approvals.requests.approve",
      "approvals.requests.reject",
      "payroll.runs.read",
      "payroll.runs.import",
      "payroll.provider.read",
      "payroll.provider.write",
      "payroll.provider.mapping.read",
      "payroll.provider.mapping.write",
      "payroll.provider.import.read",
      "payroll.provider.import.preview",
      "payroll.provider.import.apply",
      "payroll.provider.import.retention.manage",
      "bank.integration.retention.manage",
      "security.sensitive_data.audit.read",
      "ops.jobs.read",
      "ops.jobs.manage",
      "ops.jobs.run",
      "ops.dashboard.read",
      "ops.exceptions.read",
      "ops.exceptions.manage",
      "ops.retention.read",
      "ops.retention.manage",
      "ops.export_snapshot.read",
      "ops.export_snapshot.create",
      "payroll.mappings.read",
      "payroll.mappings.write",
      "payroll.runs.review",
      "payroll.runs.finalize",
      "payroll.liabilities.read",
      "payroll.liabilities.build",
      "payroll.payment.prepare",
      "payroll.payment.sync.read",
      "payroll.payment.sync.apply",
      "payroll.settlement.override.read",
      "payroll.settlement.override.request",
      "payroll.settlement.override.approve",
      "payroll.beneficiary.read",
      "payroll.beneficiary.write",
      "payroll.beneficiary.set_primary",
      "payroll.beneficiary.snapshot.read",
      "payroll.close.read",
      "payroll.close.prepare",
      "payroll.close.request",
      "payroll.close.approve",
      "payroll.close.reopen",
      "payroll.corrections.read",
      "payroll.corrections.create",
      "payroll.corrections.reverse",
      "cash.session.open",
      "cash.session.close",
      "cash.txn.read",
      "cash.txn.create",
      "cash.txn.cancel",
      "cash.txn.post",
      "cash.txn.reverse",
      "cash.report.read",
      "cari.card.read",
      "cari.card.upsert",
      "cari.doc.read",
      "cari.doc.create",
      "cari.doc.update",
      "cari.doc.post",
      "cari.doc.reverse",
      "cari.settlement.apply",
      "cari.settlement.reverse",
      "cari.report.read",
      "cari.bank.attach",
      "cari.bank.apply",
      "contract.read",
      "contract.upsert",
      "contract.activate",
      "contract.suspend",
      "contract.close",
      "contract.cancel",
      "contract.link_document",
      "revenue.schedule.read",
      "revenue.schedule.generate",
      "revenue.run.read",
      "revenue.run.create",
      "revenue.run.post",
      "revenue.run.reverse",
      "revenue.report.read",
      "intercompany.flag.read",
      "intercompany.flag.upsert",
      "fx.rate.read",
      "intercompany.pair.upsert",
      "intercompany.reconcile.run",
    ],
  },
  {
    code: "BranchOperator",
    name: "Branch Operator",
    permissions: [
      "org.tree.read",
      "org.fiscal_period.read",
      "gl.book.read",
      "gl.coa.read",
      "gl.account.read",
      "gl.journal.read",
      "gl.journal.create",
      "gl.journal.post",
      "gl.trial_balance.read",
      "cash.register.read",
      "cash.session.open",
      "cash.session.close",
      "cash.txn.read",
      "cash.txn.create",
      "cash.txn.cancel",
      "cash.report.read",
      "cari.card.read",
      "cari.doc.read",
      "cari.doc.create",
      "cari.doc.update",
      "cari.settlement.apply",
      "cari.report.read",
      "cari.bank.attach",
      "contract.read",
      "contract.upsert",
      "contract.link_document",
      "revenue.schedule.read",
      "revenue.schedule.generate",
      "revenue.run.read",
      "revenue.run.create",
      "revenue.report.read",
    ],
  },
  {
    code: "AuditorReadOnly",
    name: "Auditor (Read Only)",
    permissions: [
      "org.tree.read",
      "org.fiscal_calendar.read",
      "org.fiscal_period.read",
      "gl.book.read",
      "gl.coa.read",
      "gl.account.read",
      "gl.journal.read",
      "gl.trial_balance.read",
      "cash.register.read",
      "bank.accounts.read",
      "bank.connectors.read",
      "bank.statements.read",
      "bank.reconcile.read",
      "bank.reconcile.templates.read",
      "bank.reconcile.diffprofiles.read",
      "bank.reconcile.rules.read",
      "bank.reconcile.exceptions.read",
      "payments.batch.read",
      "bank.payments.export.read",
      "bank.payments.ack.read",
      "bank.payments.returns.read",
      "bank.approvals.policies.read",
      "bank.approvals.requests.read",
      "approvals.policies.read",
      "approvals.requests.read",
      "payroll.runs.read",
      "payroll.provider.read",
      "payroll.provider.mapping.read",
      "payroll.provider.import.read",
      "security.sensitive_data.audit.read",
      "ops.jobs.read",
      "ops.dashboard.read",
      "ops.exceptions.read",
      "ops.retention.read",
      "ops.export_snapshot.read",
      "payroll.mappings.read",
      "payroll.liabilities.read",
      "payroll.payment.sync.read",
      "payroll.settlement.override.read",
      "payroll.beneficiary.read",
      "payroll.beneficiary.snapshot.read",
      "payroll.close.read",
      "payroll.corrections.read",
      "cash.txn.read",
      "cash.report.read",
      "cari.card.read",
      "cari.doc.read",
      "cari.report.read",
      "cari.audit.read",
      "contract.read",
      "revenue.schedule.read",
      "revenue.run.read",
      "revenue.report.read",
      "fx.rate.read",
      "consolidation.run.read",
      "consolidation.report.trial_balance.read",
      "consolidation.report.summary.read",
      "consolidation.report.balance_sheet.read",
      "consolidation.report.income_statement.read",
    ],
  },
];

async function upsertCurrencies() {
  for (const [code, name, minorUnits] of BASE_CURRENCIES) {
    await query(
      `INSERT INTO currencies (code, name, minor_units)
       VALUES (?, ?, ?)
       ON DUPLICATE KEY UPDATE
         name = VALUES(name),
         minor_units = VALUES(minor_units)`,
      [code, name, minorUnits]
    );
  }
}

async function upsertCountries() {
  for (const [iso2, iso3, name, defaultCurrencyCode] of BASE_COUNTRIES) {
    await query(
      `INSERT INTO countries (iso2, iso3, name, default_currency_code)
       VALUES (?, ?, ?, ?)
       ON DUPLICATE KEY UPDATE
         iso3 = VALUES(iso3),
         name = VALUES(name),
         default_currency_code = VALUES(default_currency_code)`,
      [iso2, iso3, name, defaultCurrencyCode]
    );
  }
}

async function upsertPermissions() {
  for (const [code, description] of PERMISSIONS) {
    await query(
      `INSERT INTO permissions (code, description)
       VALUES (?, ?)
       ON DUPLICATE KEY UPDATE
         description = VALUES(description)`,
      [code, description]
    );
  }
}

async function ensureDefaultTenant(defaultTenantCode, defaultTenantName) {
  await query(
    `INSERT INTO tenants (code, name)
     VALUES (?, ?)
     ON DUPLICATE KEY UPDATE
       name = VALUES(name)`,
    [defaultTenantCode, defaultTenantName]
  );
}

async function getTenantIds() {
  const tenantRows = await query("SELECT id, code FROM tenants ORDER BY id");
  return tenantRows.rows;
}

async function getPermissionIdMap() {
  const { rows } = await query("SELECT id, code FROM permissions");
  const map = new Map();
  for (const row of rows) {
    map.set(row.code, row.id);
  }
  return map;
}

async function getRoleIdsByTenant(tenantId) {
  const { rows } = await query(
    "SELECT id, code FROM roles WHERE tenant_id = ?",
    [tenantId]
  );
  const map = new Map();
  for (const row of rows) {
    map.set(row.code, row.id);
  }
  return map;
}

async function upsertRolesForTenant(tenantId) {
  for (const role of ROLE_DEFINITIONS) {
    await query(
      `INSERT INTO roles (tenant_id, code, name, is_system)
       VALUES (?, ?, ?, TRUE)
       ON DUPLICATE KEY UPDATE
         name = VALUES(name),
         is_system = VALUES(is_system)`,
      [tenantId, role.code, role.name]
    );
  }
}

async function assignRolePermissionsForTenant(tenantId, permissionIdByCode) {
  const roleIdsByCode = await getRoleIdsByTenant(tenantId);

  for (const role of ROLE_DEFINITIONS) {
    const roleId = roleIdsByCode.get(role.code);
    if (!roleId) {
      throw new Error(`Role not found after upsert: ${role.code}`);
    }

    for (const permissionCode of role.permissions) {
      const permissionId = permissionIdByCode.get(permissionCode);
      if (!permissionId) {
        throw new Error(`Permission not found for role binding: ${permissionCode}`);
      }

      await query(
        `INSERT IGNORE INTO role_permissions (role_id, permission_id)
         VALUES (?, ?)`,
        [roleId, permissionId]
      );
    }
  }
}

export async function seedCore(options = {}) {
  const {
    defaultTenantCode = "DEFAULT",
    defaultTenantName = "Default Tenant",
    ensureDefaultTenantIfMissing = true,
  } = options;

  await runMigrations();
  await upsertCurrencies();
  await upsertCountries();
  await upsertPermissions();

  if (ensureDefaultTenantIfMissing) {
    await ensureDefaultTenant(defaultTenantCode, defaultTenantName);
  }

  const tenants = await getTenantIds();
  for (const tenant of tenants) {
    await upsertRolesForTenant(tenant.id);
  }

  const permissionIdByCode = await getPermissionIdMap();
  for (const tenant of tenants) {
    await assignRolePermissionsForTenant(tenant.id, permissionIdByCode);
  }

  return {
    tenantCount: tenants.length,
    currencyCount: BASE_CURRENCIES.length,
    countryCount: BASE_COUNTRIES.length,
    permissionCount: PERMISSIONS.length,
    roleCountPerTenant: ROLE_DEFINITIONS.length,
  };
}
